### PR TITLE
Add match with programming language and fix matching logic error

### LINKED ISSUE #80: Matching Logic Issues

### PR DESCRIPTION
**Pull request by junjunjieOng**
- Allow user to select difficulties(default: easy) -> programming language(default javascript) before matching
- Fix matching logic error
- Removed in room select programming language
- UI will revamp at later stage

### CODE REVIEW

File: assignment/assignment1/client/src/scenes/homePage/homePage.tsx [hunk 1]
```diff
@@ -71,9 +82,53 @@ const HomePage = () => {
...
+                <div className="input-container">
+                  <input type="radio" name="difficulty-radio" value={"Medium"}  defaultChecked={selectedDifficulty === "Medium"}
+                    onChange={onChangeDifficulty}/>
+                  <div className="button-medium">
+                    <label>Medium</label>
+                  </div>
+                </div>
+
+                <div className="input-container">
+                  <input type="radio" name="difficulty-radio" value={"Hard"}  defaultChecked={selectedDifficulty === "Hard"}
```
Comment (nevinlim) [inline assignment/assignment1/client/src/scenes/homePage/homePage.tsx:104]: interesting choice to use radio buttons, very good very nice

**Review by nevinlim — APPROVED** [review]
LGTM.
